// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC23_BqHqPbxtvkXhgM0uATB-HnCXfH16U',
    appId: '1:559194152902:web:28d5972a3ab84033e15cc7',
    messagingSenderId: '559194152902',
    projectId: 'notes-eee49',
    authDomain: 'notes-eee49.firebaseapp.com',
    storageBucket: 'notes-eee49.firebasestorage.app',
    measurementId: 'G-XZFW7V7JL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA2-0eY-bvjocg8Tpu9HWpNpwcIgqH1uo',
    appId: '1:559194152902:android:d3f951d88b7597c9e15cc7',
    messagingSenderId: '559194152902',
    projectId: 'notes-eee49',
    storageBucket: 'notes-eee49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSljB_cIrj54Mwut_Gg-2zCUd8qn23zZQ',
    appId: '1:559194152902:ios:47bc71ad1b1ac298e15cc7',
    messagingSenderId: '559194152902',
    projectId: 'notes-eee49',
    storageBucket: 'notes-eee49.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSljB_cIrj54Mwut_Gg-2zCUd8qn23zZQ',
    appId: '1:559194152902:ios:47bc71ad1b1ac298e15cc7',
    messagingSenderId: '559194152902',
    projectId: 'notes-eee49',
    storageBucket: 'notes-eee49.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC23_BqHqPbxtvkXhgM0uATB-HnCXfH16U',
    appId: '1:559194152902:web:5cce945d8df05aade15cc7',
    messagingSenderId: '559194152902',
    projectId: 'notes-eee49',
    authDomain: 'notes-eee49.firebaseapp.com',
    storageBucket: 'notes-eee49.firebasestorage.app',
    measurementId: 'G-8VH2YCJF9R',
  );
}
